<?php echo $this->Form->input('params.layout', array('div' => 'form-group', 'class' => 'select2-select-00 col-md-12 full-width-fix', 'label' => array('text' => __('Map Type'), 'class' => 'col-md-2 control-label'), 'between' => '<div class="col-md-10">', 'after' => '</div>', 'options' => array('1' => 'Map', '2' => 'Earth', '3' => 'Momochrome'), 'empty' => ''));?>
<?php echo $this->Form->input('params.colour', array('div' => 'form-group', 'class' => 'col-md-12 colorpicker', 'label' => array('text' => __('Monochrome colour'), 'class' => 'col-md-2 control-label'), 'between' => '<div class="col-md-10">', 'after' => '</div>'));?>
<?php echo $this->Form->input('params.zoom', array('div' => 'form-group', 'class' => 'select2-select-00 col-md-12 full-width-fix', 'label' => array('text' => __('Map Zoom'), 'class' => 'col-md-2 control-label'), 'between' => '<div class="col-md-10">', 'after' => '<span class="help-block">'.__('Higher value = closer').'</span></div>', 'options' => array(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19), 'empty' => ''));?>
<?php echo $this->Form->input('params.height', array('div' => 'form-group', 'class' => 'form-control', 'label' => array('text' => __('Map Height'), 'class' => 'col-md-2 control-label'), 'between' => '<div class="col-md-3">', 'after' => '<span class="help-block">'.__('Height of map in pixels. (Default 400px)').'</span></div>'));?>
<?php echo $this->Form->input('params.address', array('div' => 'form-group', 'class' => 'form-control', 'label' => array('text' => __('Address'), 'class' => 'col-md-2 control-label'), 'between' => '<div class="col-md-10">', 'after' => '</div>'));?>
<?php echo $this->Form->input('params.lat', array('div' => 'form-group', 'class' => 'form-control', 'label' => array('text' => __('Latitude'), 'class' => 'col-md-2 control-label'), 'between' => '<div class="col-md-3">', 'after' => '</div>'));?>
<?php echo $this->Form->input('params.lng', array('div' => 'form-group', 'class' => 'form-control', 'label' => array('text' => __('Longitude'), 'class' => 'col-md-2 control-label'), 'between' => '<div class="col-md-3">', 'after' => '</div>'));?>

<?php echo $this->Html->script(array('plugins/bootstrap-colorpicker/bootstrap-colorpicker.min.js'), array('inline' => false));?>
<?php echo $this->Html->scriptBlock("$('.colorpicker').colorpicker();", array('inline' => false));?>